apiVersion: batch/v1
kind: Job
metadata:
  name: contributor-agreement-app-job
  #generateName: camunda-bpmn-sync-poc
  annotations:
    argocd.argoproj.io/hook: Sync
    #delete hook before next sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    
spec:
  #selector:
  #  matchLabels:
  #    name: camunda-bpmn-sync-poc
  ttlSecondsAfterFinished: 400 # how long to keep pods
  activeDeadlineSeconds: 600 # how long should the job run
  backoffLimit: 1 # how many retries
  template:
    spec:
      restartPolicy: Never
      volumes:
        - name: bpmn
          emptyDir: {}
        - name: artifact-info
          configMap:
            name: contributor-agreement-app-cm
      containers:
        - name: downloader
          image: alpine:3.20
          command: ["/bin/sh", "-c"]
          args:
            - |
               
            
               echo "📄 Dumping file contents:"
               for file in /artifact/*; do
                  echo "---- $file ----"
                  cat "$file"
                  echo ""
               done
            
               echo "🎯 Specific values (if keys exist):"
            
               if [ -f /artifact/artifactName ]; then
                  echo "artifactName: $(cat /artifact/artifactName)"
               fi
            
               if [ -f /artifact/artifactUrl ]; then
                  echo "artifactUrl: $(cat /artifact/artifactUrl)"
               fi
            
               echo "✅ Done reading ConfigMap"
          volumeMounts:
            - name: bpmn
              mountPath: /bpmn
            - name: artifact-info
              mountPath: /artifact
